CarRentalSystem/urls.py
from django.contrib import admin
from django.urls import path
from frontend import views
from django.conf.urls.static import static
from django.conf import settings

# Create the appropriate url paths to associate with each html template file
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('register/', views.user_register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('search-cars-date/', views.car_list, name='search-cars-date'),
    path('reservation/<int:id>/', views.make_reservation, name='reservation'),
    path('search-cars-name/', views.car_search, name='search-cars-name'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/models.py
from django.db import models
from django.contrib.auth.models import User


# Citation: https://docs.djangoproject.com/en/5.0/topics/db/examples/one_to_one/
# Create the client account attached to the users list in the database
class ClientAccount(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


# Create the model for cars, including important fields with key attachments like locations
class Car(models.Model):
    model = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    mileage = models.PositiveIntegerField()
    cost_per_day = models.FloatField()
    cost_per_mile = models.FloatField()
    location = models.ForeignKey('RentalLocation', on_delete=models.CASCADE, related_name='cars')
    availability = models.BooleanField(default=True)
    image = models.ImageField(upload_to="car_image", blank=True, null=True, default="car_image/default_car_icon.png")

    def __str__(self):
        return self.model


# Create the model for reservations and return the associated client and car selected
class Reservation(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE, blank=True, null=True)
    client = models.ForeignKey(ClientAccount, on_delete=models.CASCADE)
    rental_date = models.DateField()
    return_date = models.DateField()

    def __str__(self):
        return str(self.client) + ' ' + str(self.car)


# Create the model for employee accounts with fields tn enter their username, pasword, location, etc.
class EmployeeAccount(models.Model):
    username = models.CharField(max_length=20, unique=True)
    password = models.CharField(max_length=20)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    location = models.ForeignKey('RentalLocation', on_delete=models.SET_NULL, null=True, blank=True)

    # Return a display of the employee's first and last name
    def __str__(self):
        return self.first_name + ' ' + self.last_name

    # Citation: https://docs.djangoproject.com/en/5.0/ref/models/instances/
    # Save account as a Django User model instance so that admins can access permission changes on it
    def save(self, *args, **kwargs):
        if not self.pk:
            # Create a new user object if this is a new employee
            user = User.objects.create_user(
                username=self.username,
                email=self.email,
                password=self.password,
                first_name=self.first_name,
                last_name=self.last_name
            )
        else:
            # Update existing user details if this employee already exists
            user = User.objects.get(username=self.username)
            user.email = self.email
            user.first_name = self.first_name
            user.last_name = self.last_name
            user.set_password(self.password)
            user.save()
        super().save(*args, **kwargs)


# Create the admin model and return their first and last name
class AdminAccount(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)

    def __str__(self):
        return self.first_name + ' ' + self.last_name


    # Save account as a Django User model instance so that admins can access permission changes on it
    def save(self, *args, **kwargs):
        if not self.pk:
            # Create a new user object if this is a new admin
            user = User.objects.create_user(
                username=self.username,
                email=self.email,
                password=self.password,
                first_name=self.first_name,
                last_name=self.last_name
            )
        else:
            # Update existing user details if this admin already exists
            user = User.objects.get(username=self.username)
            user.email = self.email
            user.first_name = self.first_name
            user.last_name = self.last_name
            user.set_password(self.password)
            user.save()
        super().save(*args, **kwargs)


# Create the rental location model to enter locations and return its name
class RentalLocation(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

frontend/forms.py
from typing import Any
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Reservation, ClientAccount, Car, EmployeeAccount, RentalLocation


# Customize the user form to include fields for an email, first name, and last name
class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control'}))

    # Associate the user form with the user model and appropriate fields
    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name", "password1", "password2")

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'


# Define a model form for creating or updating reservations in the database
class ReservationForm(forms.ModelForm):

    # Use the date time field for rental dates and read the input in the same format as the example
    rental_date = forms.DateTimeField(
        required=True,
        help_text="Example: 01/20/2024",
        input_formats=['%m/%d/%Y'],
    )
    return_date = forms.DateTimeField(
        required=True,
        help_text="Example: 01/27/2024",
        input_formats=['%m/%d/%Y'],
    )
    username = forms.CharField(required=True)

    class Meta:
        model = Reservation
        fields = ["username", "rental_date", "return_date"]


# Define a model form for creating or updating client accounts in the database
class ClientAccountForm(forms.ModelForm):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)

    class Meta:
        model = ClientAccount
        fields = ['username', 'password', 'email', 'first_name', 'last_name']

    # Create a new user object using the data from the form
    def save(self, commit=True):
        user = User.objects.create_user(
            username=self.cleaned_data['username'],
            email=self.cleaned_data['email'],
            password=self.cleaned_data['password'],
            first_name=self.cleaned_data['first_name'],
            last_name=self.cleaned_data['last_name']
        )
        # Link the new `ClientAccount` to the created `User` instance and save it
        client_account = super(ClientAccountForm, self).save(commit=False)
        client_account.user = user
        # Commit changes to the database only when the user object is ready
        if commit:
            client_account.save()
        return client_account


# Define a model form for creating or updating cars in the database
class CarForm(forms.ModelForm):
    class Meta:
        model = Car

        # Use all fields from the Car model in this form
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(CarForm, self).__init__(*args, **kwargs)

        # If the user is not an admin, attach the location to the employee's location
        if user and not user.is_superuser:
            employee = EmployeeAccount.objects.filter(user=user).first()
            if employee and employee.location:
                self.fields['location'].queryset = RentalLocation.objects.filter(id=employee.location.id)
            else:
                self.fields['location'].queryset = RentalLocation.objects.none()

frontend/views.py
from django.shortcuts import render, redirect
from .models import ClientAccount, Car, Reservation
from django.contrib.auth import login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.contrib.auth import logout
from .forms import UserRegisterForm, ReservationForm, User
from datetime import datetime
from django.db.models import Q


# Display the homepage of the website
def home(request):
    return render(request, 'frontend/home.html')


# Handle user registration with the user register form
# Citation: https://docs.djangoproject.com/en/5.0/topics/auth/default/
def user_register(request):
    # redirect to home if user is already logged in
    if request.user.is_authenticated:
        return redirect('home')
    
    # If form data is being submitted, save valid form data to create a new user
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            ClientAccount.objects.create(user=user)
            login(request, user)
            # Citation: https://docs.djangoproject.com/en/5.0/ref/contrib/messages/
            messages.success(request, "User profile successfully created.")
            return redirect('home')
    # If the request is GET, then display the form
    else:
        form = UserRegisterForm()
    return render(request, 'frontend/account/register.html', {'form': form})


# Handle user login with the authentication form
def user_login(request):
    # Redirect to home if user is already logged in
    if request.user.is_authenticated:
        return redirect('home')
    
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            # Redirect users based on the account type
            # Citation: https://medium.com/djangotube/django-roles-groups-and-permissions-introduction-a54d1070544
            if user.is_superuser or user.is_staff:
                return redirect('/admin/')
            else:
                return redirect('home')
        else:
            return redirect('login')
    else:
        form = AuthenticationForm()
    return render(request, 'frontend/account/login.html', {'form': form})


# Handle user logout when the 'signout' button is clicked
def user_logout(request):
    logout(request)
    return redirect('home')


# Check if the object is an instance of datetime and return the date
def check_date(obj):
    if type(obj) == datetime:
        return obj.date()
    else:
        return obj


# Check conflicting reservations with the given new dates by comparing them with registered dates
def conflict_reservation(car, new_rental_date, new_return_date):

    # Get the reservation dates that are associated with the selected car
    conflicting_reservations = Reservation.objects.filter(
        car = car,
        rental_date__lte = new_return_date,
        return_date__gte = new_rental_date
    )
    # Compare the dates to ensure any date within already taken time ranges are not allowed
    for reservation in conflicting_reservations:
        if (new_rental_date >= reservation.rental_date and new_rental_date <= reservation.return_date) or \
           (new_return_date >= reservation.rental_date and new_return_date <= reservation.return_date) or \
           (new_rental_date <= reservation.rental_date and new_return_date >= reservation.return_date):
            return True
    return False


# Get a car by its id and handle reservation form data
def make_reservation(request, id):
    car = Car.objects.get(pk=id)
    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            rental_date = form.cleaned_data.get('rental_date')
            return_date = form.cleaned_data.get('return_date')
            rental_date = rental_date.date()
            return_date = return_date.date()

            # Check for conflicting reservations by calling the conflict_reservation method
            if conflict_reservation(car, rental_date, return_date):
                form.add_error(None, "The selected dates are already reserved. Please enter different dates.")
            else:
                # Otherwise, associate the reservation with the car and user
                try:
                    user = User.objects.get(username=username)
                    client_account, created = ClientAccount.objects.get_or_create(user=user)
                    reservation = form.save(commit=False)
                    reservation.client = client_account
                    reservation.car = car
                    reservation.save()

                    # Keep track of how many reservations each car has
                    reservation_count = Reservation.objects.filter(car=car).count()
                    if reservation_count >= 5:
                        car.availability = False
                        car.save()
                    messages.success(request, "Reservation successfully made.")
                    return redirect('home')

                # Check to make sure the username entered is registered in the database
                except User.DoesNotExist:
                    form.add_error("username", "This username is not registered with any account.")
    else:
        form = ReservationForm(initial={'car': car})
    return render(request, 'frontend/reservation.html', {'form': form, 'car': car})


# Display the list of cars and filter available cars based on selected dates.
def car_list(request):
    car_list = Car.objects.all()
    available_cars = []
    isSearching = False

    # Get the dates and convert them to datetime objects
    if 'rental_date' in request.GET and 'return_date' in request.GET:
        rental_date_str = request.GET['rental_date']
        return_date_str = request.GET['return_date']
        rental_date = datetime.fromisoformat(rental_date_str).date()
        return_date = datetime.fromisoformat(return_date_str).date()
        isSearching = True

        # Find and display which cars are available during the specified period
        for car in car_list:
            if (not conflict_reservation(car, rental_date, return_date) and car.availability):
                available_cars.append(car)

    return render(request, 'frontend/search_date.html', {'car_list': car_list, 'available_cars': available_cars, 'isSearching': isSearching,})

# Display the list of cars and filter available cars based on searched name.
def car_search(request):
    template_name = 'frontend/search_name.html'
    context = {}
    query = request.GET.get('q')

    # Filters Car model name based on query.
    if query:
        cars = Car.objects.filter(model__icontains=query).order_by('model')

    else:
        cars = Car.objects.all

    context['cars'] = cars
    return render(request, template_name, context)

frontend/templates/frontend/car_list.html
{% extends './base.html' %}

{% block title %}Car List{% endblock %}

{% block style %} 
<link rel="stylesheet" href="../../static/css/car_list.css">
{% endblock %}

{% block content %}
<div class="search-section">
    <div class="search-modal">
        <h1>Search Cars</h1>
        <div>
            <div class="form-group">
                <label for="id_location">Location</label>
                
            </div>
            <div class="form-group">
                <label for="id_rental_date">From</label>
                
            </div>
            <div class="form-group">
                <label for="id_return_date">To</label>
                
            </div>

        </div>
    </div>
</div>
    <h1>Cars</h1>

    <form method="GET">
        <label for="rental_date">Start Date:</label>
        <input type="date" id="rental_date" name="rental_date">
        <label for="return_date">End Date:</label>
        <input type="date" id="return_date" name="return_date">
        <button type="submit">Check Availability</button>
    </form>

    <div id="available-cars-section">
        <h2 class="section-title">Available Cars</h2>
        {% if available_cars %}
            {% for car in available_cars %}
                <div class="car-container">
                    <div>
                        <h3>{{ car }}</h3>
                    </div>
                    <div class="car-desc-container">
                        <div class="car-image-container">
                            <p>{{car.image}}</p>
                            <img src={{car.image}} alt="Car Image" class="car-image">
                        </div>
                        <div class="car-desc-text-container">
                            <ul>
                                <li>Type: {{ car.type }}</li>
                                <li>Mileage: {{ car.mileage }} miles</li>
                                <li>Cost per day: ${{ car.cost_per_day }}</li>
                                <li>Cost per mile: ${{ car.cost_per_mile }}</li>
                                <li>Car location: {{ car.location }}</li>
                            </ul>
                            {% if user.is_authenticated %}
                                <form action="{% url 'reservation' car.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="submit" value="Rent Me">
                                </form>
                            {% else %}
                                <strong>Please <a href="{% url 'login' %}">log in</a> or <a href="{% url 'register' %}">register</a> to make a reservation.</strong>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h3>(There is no car available within the given time range)</h3>
        {% endif %}
    </div>

    <div id="all-cars-section">
        <h2 class="section-title">All Cars</h2>
        <div class="car-list">
            {% for car in car_list %}
                <div class="car-container">
                    <div>
                        <h3>{{ car }}</h3>
                    </div>
                    <div class="car-desc-container">
                        <div class="car-image-container">
                            <img src="/media/{{car.image}}" alt="Car Image" class="car-image">      
                        </div>
                        <div class="car-desc-text-container">
                            <ul>
                                <li>Type: {{ car.type }}</li>
                                <li>Mileage: {{ car.mileage }} miles</li>
                                <li>Cost per day: ${{ car.cost_per_day }}</li>
                                <li>Cost per mile: ${{ car.cost_per_mile }}</li>
                                <li>Car location: {{ car.location }}</li>

                                <!––Changes car status message based on its availability––>
                                {% if car.availability %}
                                    <li>Car Status: Available - At {{ car.location }}</li>
                                {% else %}
                                
                                    <!––Loops between two different reasons for an unavailable car––>
                                    {% if forloop.counter|divisibleby:2 %}
                                       <li>Car Status: Not Available - Under repair</li>
                                    {% else %}
                                        <li>Car Status: Not Available - With a customer</li>
                                    {% endif %}
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

frontend/templates/frontend/home.html
{% extends './base.html' %}

{% block title %}Car Rental System{% endblock %}

{% block style %}
<link rel="stylesheet" href="../../../static/css/home.css">
{% endblock %}

{% block content %}
<!--Allows user to search cars by date in the home screen-->
<div class="search-section">
    <div class="search-modal">
        <h1>Search Cars</h1>
        <form method="GET" action="/search-cars-date">
            <div class="search-input-container">
                <div class="form-group date-input-wrapper">
                    <label for="id_location">Start Date:</label>
                    <input type="date" name="rental_date" class="form-control" autofocus id="rental_date" required>
                </div>
                <div class="form-group date-input-wrapper">
                    <label for="id_rental_date">End Date:</label>
                    <input type="date" name="return_date" class="form-control" autofocus id="return_date" required>
                </div>
                <button type="submit" class="btn btn-primary search-button">Check Availability</button>
            </div>
        </form>
    </div>
</div>

<div class="car-type-section">
    <h2 class="section-title">Search by Car Type</h2>
    <div class="image-section">
        <div class="image-container white-text">
            <a href="#"><img class="image-car" src="../../static/image/classic.png" alt="Classic Car"></a>
            <div class="image-title">Classic Car</div>
        </div>
        <div class="image-container white-text">
            <a href="#"><img class="image-car" src="../../static/image/sedan.png" alt="Sedan"></a>
            <div class="image-title">Sedan</div>
        </div>
        <div class="image-container white-text">
            <a href="#"><img class="image-car" src="../../static/image/sports.png" alt="Sports Car"></a>
            <div class="image-title">Sports Car</div>
        </div>
        <div class="image-container white-text">
            <a href="#"><img class="image-car" src="../../static/image/SUV.png" alt="SUV"></a>
            <div class="image-title">SUV</div>
        </div>
        <div class="image-container black-text">
            <a href="#"><img class="image-car" src="../../static/image/truck.png" alt="Truck"></a>
            <div class="image-title">Truck</div>
        </div>

    </div>
</div>
<div class="location-section">
    <h2 class="section-title">Search by Location</h2>
    <div class="image-section">
        <div class="image-container white-text">
            <a href="#"><img class="image-location" src="../../static/image/Tampa.png" alt="Tampa"></a>
            <div class="image-title">Tampa</div>
        </div>
        <div class="image-container white-text">
            <a href="#"><img class="image-location" src="../../static/image/Gainesville.png" alt="Gainesville"></a>
            <div class="image-title">Gainesville</div>
        </div>
        <div class="image-container white-text">
            <a href="#"><img class="image-location" src="../../static/image/Orlando.png" alt="Orlando"></a>
            <div class="image-title">Orlando</div>
        </div>
    </div>
</div>

{% endblock %}

frontend/templates/frontend/reservation.html
{% extends './base.html' %}

{% block title %}Make a Reservation{% endblock %}

{% block style %} 
<link rel="stylesheet" href="../../static/css/reservation.css">
{% endblock %}

{% block content %}
<h1>Make a Reservation</h1>

<!-- Display the selected car information -->
<div class="car-container">
    <div>
        <h3>{{ car }}</h3>
    </div>
    <div class="car-desc-container">
        <div class="car-image-container">
            <img src="/media/{{ car.image }}" alt="Car Image" class="car-image">
        </div>
        <div class="car-desc-text-container">
            <ul>
                <li>Type: {{ car.type }}</li>
                <li>Mileage: {{ car.mileage }} miles</li>
                <li>Cost per day: ${{ car.cost_per_day }}</li>
                <li>Cost per mile: ${{ car.cost_per_mile }}</li>
                <li>Car location: {{ car.location }}</li>
            </ul>
        </div>
    </div>
</div>

<!-- Input section -->
<div id="input-section">
    <div class="form-group">
        <form action="{% url 'reservation' car.id %}" method="post">
            {% csrf_token %}
            <div class="input-wrapper form-group">
                <label for="id_username" class="input-label">Username</label>
                <input type="text" name="username" class="form-control" required id="id_username" autocomplete="username" maxlength="150" placeholder="Enter Username">
                {{ form.username.errors }}
            </div>
            <div class="input-wrapper form-group">
                <label for="id_rental_date" class="input-label">Rental Date</label>
                <input type="date" name="rental_date" class="form-control" required id="id_rental_date">
                {{ form.rental_date.errors }}
            </div>
            <div class="input-wrapper form-group">
                <label for="id_return_date" class="input-label">Return Date</label>
                <input type="date" name="return_date" class="form-control" required id="id_return_date">
                {{ form.return_date.errors }}
            </div>
            <button type="submit" class="btn btn-primary" value="Login">Submit Reservation</button>
        </form>
    </div>
</div>
{% endblock %}

frontend/templates/frontend/search_name.html
{% extends './base.html' %}

{% block title %}Search Cars by Name{% endblock %}

{% block style %} 
<link rel="stylesheet" href="../../static/css/search.css">
{% endblock %}

{% block content %}
<!--Displays search box to user where they can enter car names-->
<div class="search-section">
    <div class="search-modal">
        <h1>Search Cars</h1>
        <form action="{% url 'search-cars-name' %}" method="get">
            <div class="search-input-container">
                {% csrf_token %}
                <div class="form-group name-input-wrapper">
                    <label for="id_rental_date">Car Name:</label>
                    <input type="text" name="q" class="form-control" autofocus maxlength="150" value="{{ query }}" placeholder="ex) Tesla / Ford / BMW" required>    
                </div>
                <button type="submit" class="btn btn-primary search-button">Search</button>
            </div>
        </form>
    </div>
</div>

<!--Shows all cars if nothing is searched, if something is searched, it shows the search results-->
<div id="all-cars-section">
    <h2 class="section-title">All Cars</h2>
    <div class="car-list">
        {% if cars %}
            {% for car in cars %}
                <div class="car-container">
                    <div>
                        <h3>{{ car }}</h3>
                    </div>
                    <div class="car-desc-container">
                        <div class="car-image-container">
                            <img src="/media/{{ car.image }}" alt="Car Image" class="car-image">
                        </div>
                        <div class="car-desc-text-container">
                            <ul>
                                <li>Type: {{ car.type }}</li>
                                <li>Mileage: {{ car.mileage }} miles</li>
                                <li>Cost per day: ${{ car.cost_per_day }}</li>
                                <li>Cost per mile: ${{ car.cost_per_mile }}</li>
                                <li>Car location: {{ car.location }}</li>
                                <!--Changes car status message based on its availability-->
                                {% if car.availability %}
                                    <li>Car Status: Available - At {{ car.location }}</li>
                                {% else %}

                                    <!--Loops between two different reasons for an unavailable car-->
                                    {% if forloop.counter|divisibleby:2 %}
                                        <li>Car Status: Not Available - Under repair</li>
                                    {% else %}
                                        <li>Car Status: Not Available - With a customer</li>
                                    {% endif %}
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            {% for car in car_list %}
                <div class="car-container">
                    <div>
                        <h3>{{ car }}</h3>
                    </div>
                    <div class="car-desc-container">
                        <div class="car-image-container">
                            <img src="/media/{{ car.image }}" alt="Car Image" class="car-image">
                        </div>
                        <div class="car-desc-text-container">
                            <ul>
                                <li>Type: {{ car.type }}</li>
                                <li>Mileage: {{ car.mileage }} miles</li>
                                <li>Cost per day: ${{ car.cost_per_day }}</li>
                                <li>Cost per mile: ${{ car.cost_per_mile }}</li>
                                <li>Car location: {{ car.location }}</li>

                                <!-- Changes car status message based on its availability -->
                                {% if car.availability %}
                                    <li>Car Status: Available - At {{ car.location }}</li>
                                {% else %}

                                    <!-- Loops between two different reasons for an unavailable car -->
                                    {% if forloop.counter|divisibleby:2 %}
                                        <li>Car Status: Not Available - Under repair</li>
                                    {% else %}
                                        <li>Car Status: Not Available - With a customer</li>
                                    {% endif %}
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
</div>

{% endblock %}